### ISSUE TITLE
Crash when trying to switch dark mode on or off 

### ISSUE THREAD

**Issue by hossainsafwan** [Gear61/tcg-android-archive-and-feedback#24]
## Description
The app crashes when trying to turn dark mode on or off.
This crash is only observed in the release and not in the debug build (master branch).

### Release Build

https://user-images.githubusercontent.com/22313316/157806137-75674815-60ec-47e8-b660-ef8b8f9437d4.mp4

### Debug Build

https://user-images.githubusercontent.com/22313316/157806110-87e3e5d4-7879-4f9f-81ab-fbcaa6430bfb.mp4

**Comment by veganaize** [comment]
Which version of Android are you using (in `Settings` -> `System` -> `About phone` -> `Software info` -> `Android version`)?  

Have you tried an [OTA update](https://support.google.com/android/answer/7680439?hl=en)?

**Comment by Gear61** [comment]
I think I found this crash before. It had to do with the poor way I was restoring fragments. @hossainsafwan Let me know if you are still seeing this issue!

**Comment by hossainsafwan** [comment]
I am no longer seeing the issue in production. Thank you for the update.
